# AI Fragility Tracker - News Sources Configuration
# Each source is checked during pipeline runs

sources:
  # Primary tech news RSS feeds
  - name: "TechCrunch AI"
    url: "https://techcrunch.com/category/artificial-intelligence/feed/"
    type: "rss"
    enabled: true
    priority: 1
    
  - name: "VentureBeat AI"
    url: "https://venturebeat.com/category/ai/feed/"
    type: "rss"
    enabled: true
    priority: 1
    
  - name: "Ars Technica"
    url: "https://feeds.arstechnica.com/arstechnica/technology-lab"
    type: "rss"
    enabled: true
    priority: 2
    
  - name: "The Verge"
    url: "https://www.theverge.com/rss/index.xml"
    type: "rss"
    enabled: true
    priority: 2

  - name: "Wired"
    url: "https://www.wired.com/feed/rss"
    type: "rss"
    enabled: true
    priority: 2
    
  - name: "MIT Technology Review"
    url: "https://www.technologyreview.com/feed/"
    type: "rss"
    enabled: true
    priority: 1

# Lab name patterns for classification
lab_patterns:
  openai:
    - "openai"
    - "chatgpt"
    - "gpt-4"
    - "gpt-5"
    - "sam altman"
    - "dall-e"
    - "sora"
    
  anthropic:
    - "anthropic"
    - "claude"
    - "dario amodei"
    - "daniela amodei"
    
  deepmind:
    - "deepmind"
    - "google deepmind"
    - "gemini"
    - "demis hassabis"
    
  xai:
    - "xai"
    - "x.ai"
    - "grok"
    - "elon musk ai"
    - "colossus"
    
  meta:
    - "meta ai"
    - "llama"
    - "meta's ai"
    - "yann lecun"

# Dimension keywords for classification
dimension_patterns:
  compute_chips:
    - "nvidia"
    - "gpu"
    - "h100"
    - "b200"
    - "blackwell"
    - "hopper"
    - "accelerator"
    - "chip"
    - "semiconductor"
    - "tpu"
    - "asic"
    - "datacenter"
    - "compute"
    - "training cluster"
    
  cloud:
    - "azure"
    - "aws"
    - "amazon web services"
    - "google cloud"
    - "gcp"
    - "hyperscaler"
    - "cloud partnership"
    - "cloud infrastructure"
    - "oracle cloud"
    
  policy:
    - "regulation"
    - "antitrust"
    - "ftc"
    - "doj"
    - "eu ai act"
    - "export control"
    - "sanctions"
    - "compliance"
    - "safety"
    - "congress"
    - "legislation"
    
  demand:
    - "revenue"
    - "valuation"
    - "funding"
    - "subscriber"
    - "customer"
    - "enterprise"
    - "monetization"
    - "pricing"
    - "market share"
    
  resilience:
    - "diversif"
    - "multi-cloud"
    - "redundan"
    - "backup"
    - "hedge"
    - "alternative"
    - "mitigation"

# Impact signal keywords
impact_patterns:
  positive_fragility:  # Increases fragility score
    - "exclusive"
    - "lock-in"
    - "dependent"
    - "shortage"
    - "constraint"
    - "investigation"
    - "scrutiny"
    - "decline"
    - "challenge"
    - "concern"
    - "risk"
    - "delay"
    
  negative_fragility:  # Decreases fragility score (resilience)
    - "diversif"
    - "expand"
    - "partner"
    - "multi"
    - "alternative"
    - "redundan"
    - "secure"
    - "contract"
    - "growth"
    - "strong"
